name: Build Linux Executable

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name MarkEd \
                   --onefile \
                   --windowed \
                   --icon icon.ico \
                   --add-data "icon.ico:." \
                   main.py
    
    - name: Get version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Package
      run: |
        mkdir -p deb/DEBIAN deb/usr/local/bin
        cat > deb/DEBIAN/control << EOF
        Package: MarkEd
        Version: ${VERSION#v}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: T9Air <aymorg1@gmail.com>
        Description: MarkEd
         An intuitive, cross-platform, real-time Markdown editor built with Python.
        EOF
        cp dist/MarkEd deb/usr/local/bin/
        dpkg-deb --build deb "MarkEd-${{ env.VERSION }}.deb"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MarkEd-linux
        path: MarkEd-${{ env.VERSION }}.deb

    - name: Attach to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MarkEd-${{ env.VERSION }}.deb
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}